### ISSUE TITLE
Multiple matches

### ISSUE THREAD

**Issue by HadarNahshon** [orbit-1690/scouting2020#39]
Building on #38, we want to be able to manage more than a single match.
- [x] Rename `ScoutingMain` to `Match`
- [ ] Wrap `Match` in a new `Main` that supports multiple matches
- [ ] Move the `export to csv` button from `Match` to `Main` so that all matches are downloaded as a single CSV table.

**Comment by itasgaming** [comment]
what did you mean on:
Wrap Match in a new Main that supports multiple matches
why do I need multiple matches?

**Comment by HadarNahshon** [comment]
We send each match separately, so there is no need for it.
I'm closing the issue.
